add signature_algorithm_parameters to certificate
pyca/cryptography pull request #8795
Opened 2023-04-23 17:16 UTC by reaperhulk

this allows easier verification of cert signatures, but more specifically allows PSS signature verification

missing docs and tests and possibly we'll change one approach

2023-04-24 16:36 UTC, alex commented on src/rust/cryptography-x509/src/common.rs
> +    },
This can just be `PSS_DEFAULT_HASH_ALG`, yes?

2023-04-24 16:38 UTC, alex commented on src/rust/cryptography-x509/src/common.rs
> +pub const PSS_DEFAULT_HASH_ALG: AlgorithmIdentifier<'_> = AlgorithmIdentifier {
This should have SHA1 in the name, instead of default I think?

2023-04-24 16:38 UTC, alex commented on src/rust/cryptography-x509/src/common.rs
> +pub const PSS_DEFAULT_MASK_GEN_ALG: MaskGenAlgorithm<'_> = MaskGenAlgorithm {
Same re: SHA1

2023-04-24 16:43 UTC, alex commented on src/rust/src/x509/certificate.rs
> +static HASH_OIDS_TO_HASH: Lazy<HashMap<&asn1::ObjectIdentifier, &str>> = Lazy::new(|| {
Move to top of file I think

2023-04-29 15:29 UTC, alex requested changes
Needs the NULL TLV issue resolved.

2023-05-07 17:38 UTC, reaperhulk commented
This is ready for review but also needs a rust-asn1 release to be mergeable.

2023-05-07 20:07 UTC, alex approved these changes

2023-05-07 20:26 UTC, merged